### ISSUE TITLE
El menu de venue no funciona

### ISSUE THREAD

**Issue by alesanchezr** [alesanchezr/bmw-website#9]
El menu de venue deberia functionar llevando al usuario a la misma pagina pero haciedno scrol a la seccion donde se habla de eso, eso lo puedes lograr usando ID

http://www.webweaver.nu/html-tips/link-within-a-page.shtml

**Comment by caenavgu** [comment]
Solo me falta 369 tour y weddings que no se a que seccion deben llevar.

**Comment by alesanchezr** [comment]
El 360 view te debe llevar a al tour 360 que tiene google de ese venue. No todos tienes asi q el boton debe aparecer solo si ese venue tiene.

Igual el link de "weddings", solo debe aparecer si el venue tiene el link hacia las weddings.

Son dos custom fields, el de 360 permite poner el iframe de google maps y el de weddings permite poner un URL.

**Comment by caenavgu** [comment]
disculpa pero que quieres decir cuando dices "Igual el link de "weddings", solo debe aparecer si el venue tiene el link hacia las weddings" a que nos referimos con weddings e este caso. El 360 ya esta

**Comment by caenavgu** [comment]
Done!
